### ISSUE TITLE
Request - Share your Mini-Graph-Card Yaml =)

### ISSUE THREAD

**Issue by DeFlanko** [viktak/ha-cc-openweathermap_all#12]
I too LOVE that mini-graph-card -- use it for just about everything. 

Would be willing to share your yaml you used in the screenshot?

**Comment by viktak** [comment]
```yaml
  - type: horizontal-stack
    cards:
      - type: custom:mini-graph-card
        name: UV Index
        icon: mdi:gauge
        hours_to_show: 24
        points_per_hour: 6
        hour24: true
        show:
          extrema: true
        entities:
          - entity: sensor.owm_ultraviolet_index
```
and so on, and so on... :)

**Comment by DeFlanko** [comment]
Thank you !

**Comment by DeFlanko** [comment]
I wanted to update you with my version -- using several sources for the color grading -- in hopes maybe others find this too:
* https://www.breeze-technologies.de/blog/what-is-an-air-quality-index-how-is-it-calculated/
* https://en.wikipedia.org/wiki/Air_quality_index#CAQI
* https://en.wikipedia.org/wiki/Ultraviolet_index
* https://openweathermap.org/api/air-pollution

```YAML 
type: vertical-stack
cards:
  - type: custom:mini-graph-card
    icon: mdi:gauge
    labels: true
    hours_to_show: 24
    points_per_hour: 6
    line_width: 3
    hour24: true
    animate: true
    color_thresholds:
      - value: 5
        color: '#800080'
      - value: 4
        color: '#ff0000'
      - value: 3
        color: '#ffa500'
      - value: 2
        color: '#ffff00'
      - value: 1
        color: '#52c900'
    show:
      extrema: true
      name_adaptive_color: true
      icon_adaptive_color: true
    entities:
      - entity: sensor.owm_pollution_overall_air_quality
        name: Overall Air Quality
  - type: custom:mini-graph-card
    labels: true
    name_adaptive_color: true
    hours_to_show: 24
    points_per_hour: 6
    line_width: 3
    hour24: true
    animate: true
    color_thresholds:
      - value: 241
        color: '#800080'
      - value: 240
        color: '#ff0000'
      - value: 180
        color: '#ffa500'
      - value: 120
        color: '#ffff00'
      - value: 60
        color: '#52c900'
    show:
      extrema: true
      name_adaptive_color: true
      icon_adaptive_color: true
    entities:
      - entity: sensor.owm_pollution_ozone_o3
        name: Ozone (O3)
  - type: custom:mini-graph-card
    labels: true
    name_adaptive_color: true
    hours_to_show: 24
    points_per_hour: 6
    line_width: 3
    hour24: true
    animate: true
    color_thresholds:
      - value: 181
        color: '#800080'
      - value: 180
        color: '#ff0000'
      - value: 90
        color: '#ffa500'
      - value: 50
        color: '#ffff00'
      - value: 25
        color: '#52c900'
    show:
      extrema: true
      name_adaptive_color: true
      icon_adaptive_color: true
    entities:
      - entity: sensor.owm_pollution_coarse_particles_pm10
        name: Coarse Particles
  - type: custom:mini-graph-card
    labels: true
    name_adaptive_color: true
    hours_to_show: 24
    points_per_hour: 6
    line_width: 3
    hour24: true
    animate: true
    color_thresholds:
      - value: 11
        color: '#800080'
      - value: 10
        color: '#ff0000'
      - value: 7
        color: '#ffa500'
      - value: 5
        color: '#ffff00'
      - value: 2
        color: '#52c900'
    show:
      extrema: true
      name_adaptive_color: true
      icon_adaptive_color: true
    entities:
      - entity: sensor.owm_pollution_nitrogen_monoxide_no
        name: Nitrogen Monoxide (NO)
  - type: custom:mini-graph-card
    labels: true
    name_adaptive_color: true
    hours_to_show: 24
    points_per_hour: 6
    line_width: 3
    hour24: true
    animate: true
    color_thresholds:
      - value: 150001
        color: '#800080'
      - value: 150000
        color: '#ff0000'
      - value: 15000
        color: '#ffa500'
      - value: 37.5
        color: '#ffff00'
      - value: 7.5
        color: '#52c900'
    show:
      extrema: true
      name_adaptive_color: true
      icon_adaptive_color: true
    entities:
      - entity: sensor.owm_pollution_ammonia_nh3
        name: Ammonia (NH3)
```
![image](https://user-images.githubusercontent.com/5233969/197355080-a4c5ea8c-bac5-4c9e-aa54-e90ed27c452f.png)
