### ISSUE TITLE
[EXAMPLE] References for defining AQI graphs bounds and color transitions

### ISSUE THREAD

**Issue by dimankiev** [viktak/ha-cc-openweathermap_all#13]
# Example configuration
Hello, I would like to share some resources I used to configure graphs
You could include it in examples, or maybe create a wiki and include my shared materials alongside yours, in a "Users examples" section
![image](https://user-images.githubusercontent.com/30737847/212434117-c3b42d6c-0c94-4af5-af1f-fe48b0844e7d.png)
## Custom components
 - https://github.com/kalkih/mini-graph-card
 - https://github.com/thomasloven/lovelace-layout-card
 - https://github.com/RossMcMillan92/lovelace-collapsable-cards
## Pollution levels, value conversion
Safety boundaries: https://www.airnow.gov/sites/default/files/2020-05/aqi-technical-assistance-document-sept2018.pdf
Conversion from ppb: https://www2.dmu.dk/atmosphericenvironment/expost/database/docs/ppm_conversion.pdf
For ppm just multiply the value by coefficient, then by 1000
## YAML for this AQI subview
```yaml
views:
  - theme: Google Dark Theme
    title: AQI
    path: aqi
    subview: true
    icon: mdi:air-filter
    type: custom:horizontal-layout
    badges: []
    cards:
      - show_current: true
        show_forecast: false
        type: weather-forecast
        entity: weather.home_assistant
        name: Weather summary
        secondary_info_attribute: wind_speed
        theme: Google Dark Theme
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                show:
                  extrema: true
                hours_to_show: 8
                points_per_hour: 1
                min_bound_range: 2
                entities:
                  - entity: sensor.owm_pollution_coarse_particles_pm10
                    name: PM10
                    show_state: true
                    show_indicator: true
                    state_adaptive_color: true
                color_thresholds:
                  - value: 0
                    color: '#a8eb34'
                  - value: 54
                    color: '#ebc334'
                  - value: 154
                    color: '#eb7734'
                  - value: 254
                    color: '#eb3434'
                  - value: 354
                    color: '#7734eb'
                  - value: 424
                    color: '#eb3458'
                  - value: 504
                    color: '#7e0024'
              - type: custom:mini-graph-card
                show:
                  extrema: true
                hours_to_show: 8
                points_per_hour: 1
                min_bound_range: 2
                entities:
                  - entity: sensor.owm_pollution_fine_particles_pm2_5
                    name: PM2.5
                    show_state: true
                    show_indicator: true
                    state_adaptive_color: true
                color_thresholds:
                  - value: 0
                    color: '#a8eb34'
                  - value: 12
                    color: '#ebc334'
                  - value: 35.4
                    color: '#eb7734'
                  - value: 55.4
                    color: '#eb3434'
                  - value: 150.4
                    color: '#7734eb'
                  - value: 250.4
                    color: '#eb3458'
                  - value: 350.4
                    color: '#7e0024'
          - type: custom:collapsable-cards
            title: Pollutants info
            cards:
              - type: markdown
                content: >-
                  **10μm Particulate Matter**

                  Fly Ash, Dust (Settling, Cement), Mould Spores, Pollen

                  **2.5μm Particulate Matter**

                  Settling Dust, Fly Ash, Oil Smoke, Mould Spores, Dust Mite
                  Allergens, Bacteria, Other Allergens
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                show:
                  extrema: true
                hours_to_show: 8
                points_per_hour: 1
                min_bound_range: 0.5
                entities:
                  - entity: sensor.owm_pollution_ammonia_nh3
                    name: Ammonia (NH3)
                    show_state: true
                    show_indicator: true
                    state_adaptive_color: true
                color_thresholds:
                  - value: 0
                    color: '#a8eb34'
                  - value: 5
                    color: '#ebc334'
                  - value: 15
                    color: '#eb7734'
                  - value: 50
                    color: '#eb3434'
                  - value: 100
                    color: '#7734eb'
                  - value: 150
                    color: '#eb3458'
                  - value: 200
                    color: '#7e0024'
              - type: custom:mini-graph-card
                show:
                  extrema: true
                hours_to_show: 8
                points_per_hour: 1
                min_bound_range: 5
                entities:
                  - entity: sensor.owm_pollution_carbon_monoxide_co
                    name: Carbon monoxide (CO)
                    show_state: true
                    show_indicator: true
                    state_adaptive_color: true
                color_thresholds:
                  - value: 0
                    color: '#a8eb34'
                  - value: 5038
                    color: '#ebc334'
                  - value: 10763
                    color: '#eb7734'
                  - value: 14198
                    color: '#eb3434'
                  - value: 17633
                    color: '#7734eb'
                  - value: 34808
                    color: '#eb3458'
                  - value: 46258
                    color: '#7e0024'
          - type: custom:collapsable-cards
            title: Pollutants info
            cards:
              - type: markdown
                content: >-
                  The toxicity of **ammonia** solutions does not usually cause
                  problems for humans and other mammals, as a specific mechanism
                  exists to prevent its build-up in the bloodstream.

                  **Carbon monoxide** poisoning is the most common type of fatal
                  air poisoning. It is relatively undetectable. 667k μg/m3 may
                  cause up to 50% of the body's hemoglobin to convert to
                  carboxyhemoglobin, which may result in seizure, coma, and
                  fatality.
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                show:
                  extrema: true
                hours_to_show: 8
                points_per_hour: 1
                min_bound_range: 2
                entities:
                  - entity: sensor.owm_pollution_sulphur_dioxide_so2
                    name: Sulphur Dioxide (SO2)
                    show_state: true
                    show_indicator: true
                    state_adaptive_color: true
                color_thresholds:
                  - value: 0
                    color: '#a8eb34'
                  - value: 91.7
                    color: '#ebc334'
                  - value: 196.5
                    color: '#eb7734'
                  - value: 484.7
                    color: '#eb3434'
                  - value: 796.48
                    color: '#7734eb'
                  - value: 1582.48
                    color: '#eb3458'
                  - value: 2106.48
                    color: '#7e0024'
              - type: custom:mini-graph-card
                show:
                  extrema: true
                hours_to_show: 8
                points_per_hour: 1
                min_bound_range: 2
                entities:
                  - entity: sensor.owm_pollution_nitrogen_dioxide_no2
                    name: Nitrogen Dioxide (NO2)
                    show_state: true
                    show_indicator: true
                    state_adaptive_color: true
                color_thresholds:
                  - value: 0
                    color: '#a8eb34'
                  - value: 99.64
                    color: '#ebc334'
                  - value: 188
                    color: '#eb7734'
                  - value: 676.8
                    color: '#eb3434'
                  - value: 1220.12
                    color: '#7734eb'
                  - value: 2348.12
                    color: '#eb3458'
                  - value: 3100.12
                    color: '#7e0024'
          - type: custom:collapsable-cards
            title: Pollutants info
            cards:
              - type: markdown
                content: >-
                  **Sulfur dioxide** can damage trees and plants, inhibit plant
                  growth, and damage sensitive ecosystems and waterways. It also
                  can contribute to respiratory illness and aggravate existing
                  heart and lung conditions.

                  Breathing air with a high concentration of **NO2** can
                  irritate airways in the human respiratory system. Such
                  exposures over short periods can aggravate respiratory
                  diseases, particularly asthma, leading to respiratory symptoms
                  (such as coughing, wheezing or difficulty breathing)
```

**Comment by dimankiev** [comment]
Adding outdoor air quality whitepaper as reference for safety boundaries
https://www.renesas.com/us/en/document/whp/outdoor-air-quality-white-paper

**Comment by xox-ua** [comment]
![зображення_2024-03-18_001046682](https://github.com/viktak/ha-cc-openweathermap_all/assets/23065754/22302566-39e5-4605-a667-5c8de6d230a4)
No creates charts. :(

**Comment by viktak** [comment]
<img width="1130" alt="image" src="https://github.com/viktak/ha-cc-openweathermap_all/assets/12509879/ee11782c-1344-420e-8730-a9409b328486">

@xox-ua  yes creates charts :)

First of all, you should provide a bit more details on what/how you are trying to achieve it. Second, as long as the number are working, this component is OK and the problem leas somewhere else.

**Comment by xox-ua** [comment]
1. I want to see the same beauty as yours. But with a light design.
2. Integration works for about two days.

What do I have?
Mini PC, Proxmox, HAOS, MariaDB.
Code like above (from dimankiev).

Lovelace:
mini-graph card
lovelace-layout-card
lovelace-collapsable-cards
apexcharts-card

In configuration.yaml:
sensor:
   - platform: openweathermap_all
     api_key: 025eb9bla-blac5e19
     latitude: bla-bla632126048142
     longitude: bla-bla889101147652

No errors in logs. :(

**Comment by viktak** [comment]
As I mentioned in the previous reply, as long as the numbers show up correctly, this component works fine. If you have a problem with the graphs, you need to look into those. Check if they are correctly installed (maybe remove it and install it again), etc.

Here is a sample of what I have:
```yaml
      - type: custom:mini-graph-card
        name: Fine Particle Matter (PM2.5)
        hours_to_show: 24
        points_per_hour: 6
        hour24: true
        icon: mdi:scatter-plot
        show:
          extrema: true
        entities:
          - entity: sensor.owm_pollution_fine_particles_pm2_5
```

I'm afraid, I can't assist you with the graph component as I am only a fellow user of it.
