### ISSUE TITLE
no sensors created

### ISSUE THREAD

**Issue by wuast94** [viktak/ha-cc-openweathermap_all#6]
i installed via hacs and created the config

```
# Open Weathermap All
sensor:
    - platform: openweathermap_all
      api_key: !secret openweather
      latitude: xx.xxxxxxx
      longitude: x.xxxxxxx
```

and restarted but no entities are created

**Comment by viktak** [comment]
Any errors in the log?

**Comment by viktak** [comment]
Also, the indentation looks a bit off to me. Are you sure the `- platform: ...` section is indented by only two spaces? It looks four spaces here.

**Comment by wuast94** [comment]
i copied this out of your repo readme, and HA say its all fine when checking the config. but i changed this to two spaces now. 

i can only see that the custom component is loaded in logs:
`2021-06-25 09:25:06 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration openweathermap_all which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant`

from there on i dont see any entry about this plugin :/

**Comment by viktak** [comment]
I have the following configuration in my current HA installation that works:
`owm.yaml`:
```yaml
- platform: openweathermap_all
  api_key: !secret openweathermap_api_key
  latitude: !secret home_lat
  longitude: !secret home_lon
```
`configuration.yaml`:
```yaml
sensor: !include_dir_merge_list sensors/
```
If this doesn't work for, I suggest you check the secret definitions. Even better, in the first instance, replace the secret "stuff" with the actual values to be sure.

Let me know how it goes, if there is any difference.
